[packages."digital.dutton.essentials.store"]
description = "Installs and automatically updates the GrapheneOS Essentials app suite."
channel = "stable"

[packages."digital.dutton.essentials.maps"]
description = "Private, offline-first maps and navigation."
channel = "stable"

[packages."digital.dutton.essentials.messages"]
description = "Private SMS and MMS messaging."
channel = "stable"
